# Generated by Django 4.2 on 2023-07-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minformation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logininfo',
        ),
    ]
